CREATE TABLE "player_builds" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"is_public" boolean DEFAULT false NOT NULL,
	"archetype" text,
	"acceleration_trait" text,
	"forehand_power" integer,
	"forehand_consistency" integer,
	"forehand_precision" integer,
	"backhand_power" integer,
	"backhand_consistency" integer,
	"backhand_precision" integer,
	"service_power" integer,
	"service_consistency" integer,
	"service_precision" integer,
	"forehand_volley" integer,
	"backhand_volley" integer,
	"smash" integer,
	"net_presence" integer,
	"focus" integer,
	"counter" integer,
	"lob" integer,
	"drop_shot" integer,
	"top_spin" integer,
	"speed" integer,
	"stamina" integer,
	"muscle_tone" integer,
	"short_term_form" integer,
	"points" integer,
	"character_image_url" text,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "player_builds_player_id_unique" UNIQUE("player_id")
);
--> statement-breakpoint
ALTER TABLE "player_builds" ADD CONSTRAINT "player_builds_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE cascade ON UPDATE no action;